import type { Metadata } from "next"
import "./globals.css"
import Nav from "@/app/components/Nav"
import GlobalContextProvider from "@/app/context/Global"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider isLoggedIn={false} user={{ username: "" }}>
          <Nav />
          <div className={"pt-20"}>{children}</div>
        </GlobalContextProvider>
      </body>
    </html>
  )
}
