import type { Metadata } from "next"
import "./globals.css"
import Nav from "@/app/components/Nav"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Nav />
      <body className={"pt-20"}>{children}</body>
    </html>
  )
}
